# Generated by Django 3.2.11 on 2026-07-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0048_campenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to='CSAA.user'),
        ),
    ]
